// https://github.com/aws/aws-cdk/blob/v2.263.0/packages/aws-cdk-lib/aws-rds/test/serverless-cluster-from-snapshot.test.ts
//
// Aurora Serverless v1 was RETIRED by AWS -- see the module-level TERRACONSTRUCTS note in
// `../../../../src/aws/storage/rds/serverless-cluster.ts`. This is a FULL port for API/migration
// parity; individual behavioral gaps are documented inline with TERRACONSTRUCTS DEVIATION/TODO notes
// at each call site, mirroring the identical omissions already established for
// `DatabaseClusterFromSnapshot` in `./cluster.test.ts`.

import {
  rdsCluster,
  dbSubnetGroup,
  secretsmanagerSecret,
  dataAwsSecretsmanagerRandomPassword,
} from "@cdktn/provider-aws";
import { App, Testing } from "cdktn";
import "cdktn/lib/testing/adapters/jest";
import { AwsStack } from "../../../../src/aws";
import * as compute from "../../../../src/aws/compute";
import * as encryption from "../../../../src/aws/encryption";
import * as rds from "../../../../src/aws/storage/rds";
import { Template } from "../../../assertions";

const environmentName = "Test";
const gridUUID = "a123e4567-e89b-12d3";
const providerConfig = { region: "us-east-1" };
// snapshot tests must not use the default local backend - its state file path
// is machine-dependent and would leak into the snapshot
const gridBackendConfig = {
  address: "http://localhost:3000",
};

function testStack(app?: App, stackId?: string): AwsStack {
  return new AwsStack(app ?? Testing.app(), stackId ?? "MyStack", {
    environmentName,
    gridUUID,
    providerConfig,
    gridBackendConfig,
  });
}

describe("serverless cluster from snapshot", () => {
  test("create a serverless cluster from a snapshot", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");

    // WHEN
    new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
      vpc,
      snapshotIdentifier: "my-snapshot",
    });

    // THEN
    const t = new Template(stack);
    t.expect.toHaveResourceWithProperties(rdsCluster.RdsCluster, {
      engine: "aurora-mysql",
      copy_tags_to_snapshot: true,
      db_cluster_parameter_group_name: "default.aurora-mysql5.7",
      engine_mode: "serverless",
      snapshot_identifier: "my-snapshot",
      storage_encrypted: true,
    });
    t.expect.toHaveResourceWithProperties(dbSubnetGroup.DbSubnetGroup, {
      description: "Subnets for ServerlessDatabase database",
    });
  });

  test("can generate a new snapshot password", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");

    // WHEN
    new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
      vpc,
      snapshotIdentifier: "mySnapshot",
      credentials: rds.SnapshotCredentials.fromGeneratedSecret("admin", {
        excludeCharacters: '"@/\\',
      }),
    });

    // THEN
    // TERRACONSTRUCTS DEVIATION: mirrors `DatabaseClusterFromSnapshot`'s
    // `renderClusterSnapshotCredentials`/`Secret._generatedPassword` house pattern (see
    // `./cluster.ts`) rather than upstream's CFN dynamic-reference (`{{resolve:secretsmanager:...}}`)
    // syntax.
    const t = new Template(stack);
    const [clusterResource] = t.resourceTypeArray(
      rdsCluster.RdsCluster,
    ) as any[];
    expect(clusterResource.master_username).toBeUndefined();
    expect(clusterResource.master_password).toBeDefined();
    expect(clusterResource.lifecycle).toEqual({
      ignore_changes: ["master_password"],
    });
    t.expect.toHaveResourceWithProperties(
      secretsmanagerSecret.SecretsmanagerSecret,
      {
        description: expect.stringContaining("Generated by the CDK for stack:"),
      },
    );
    t.expect.toHaveDataSourceWithProperties(
      dataAwsSecretsmanagerRandomPassword.DataAwsSecretsmanagerRandomPassword,
      {
        exclude_characters: '"@/\\',
        password_length: 30,
      },
    );
  });

  test("fromGeneratedSecret with replica regions", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");

    // WHEN
    new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
      vpc,
      snapshotIdentifier: "mySnapshot",
      credentials: rds.SnapshotCredentials.fromGeneratedSecret("admin", {
        replicaRegions: [{ region: "eu-west-1" }],
      }),
    });

    // THEN
    const t = new Template(stack);
    t.expect.toHaveResourceWithProperties(
      secretsmanagerSecret.SecretsmanagerSecret,
      {
        replica: [{ region: "eu-west-1" }],
      },
    );
  });

  test("throws if generating a new password without a username", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");

    // WHEN
    expect(
      () =>
        new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
          engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
          vpc,
          snapshotIdentifier: "mySnapshot",
          credentials: { generatePassword: true } as rds.SnapshotCredentials,
        }),
    ).toThrow(
      /`credentials` `username` must be specified when `generatePassword` is set to true/,
    );
  });

  test("can set a new snapshot password from an existing password", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");

    // WHEN
    new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
      vpc,
      snapshotIdentifier: "mySnapshot",
      credentials: rds.SnapshotCredentials.fromPassword("mysecretpassword"),
    });

    // THEN
    const t = new Template(stack);
    const [clusterResource] = t.resourceTypeArray(
      rdsCluster.RdsCluster,
    ) as any[];
    expect(clusterResource.master_username).toBeUndefined();
    expect(clusterResource.master_password).toEqual("mysecretpassword");
  });

  // TODO: omitted -- "can set a new snapshot password from an existing Secret" exercises
  // `SnapshotCredentials.fromSecret()`, which depends on `ISecret.secretValueFromJson` -- not ported
  // in this repo (see the commented-out `SnapshotCredentials.fromSecret` in
  // `../../../../src/aws/storage/rds/props.ts`, and the identical omission exercised by
  // "rejects snapshotCredentials created with SnapshotCredentials.fromSecret()" in `./cluster.test.ts`) --
  // https://github.com/aws/aws-cdk/blob/v2.263.0/packages/aws-cdk-lib/aws-rds/test/serverless-cluster-from-snapshot.test.ts#L139-L162
  test("rejects credentials created with SnapshotCredentials.fromSecret()", () => {
    const stack = testStack();
    const vpc = new compute.Vpc(stack, "VPC");
    const secret = new rds.DatabaseSecret(stack, "DBSecret", {
      username: "admin",
      encryptionKey: new encryption.Key(stack, "PasswordKey"),
    });

    expect(
      () =>
        new rds.ServerlessClusterFromSnapshot(stack, "ServerlessDatabase", {
          engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
          vpc,
          snapshotIdentifier: "mySnapshot",
          credentials: { secret } as unknown as rds.SnapshotCredentials,
        }),
    ).toThrow(
      /SnapshotCredentials with an existing `secret` are not supported in TerraConstructs/,
    );
  });
});
