// https://github.com/aws/aws-cdk/blob/v2.263.0/packages/aws-cdk-lib/aws-docdb/lib/database-secret.ts

import type { Construct } from "constructs";
import { AwsStack } from "../../aws-stack";
import * as secretsmanager from "../../encryption";
import type { IKey } from "../../encryption";

/**
 * Construction properties for a DatabaseSecret.
 */
export interface DatabaseSecretProps {
  /**
   * The username.
   */
  readonly username: string;

  /**
   * The KMS key to use to encrypt the secret.
   *
   * @default default master key
   */
  readonly encryptionKey?: IKey;

  /**
   * The physical name of the secret
   *
   * @default Secretsmanager will generate a physical name for the secret
   */
  readonly secretName?: string;

  /**
   * The master secret which will be used to rotate this secret.
   *
   * @default - no master secret information will be included
   */
  readonly masterSecret?: secretsmanager.ISecret;

  /**
   * Characters to not include in the generated password.
   *
   * @default "\"@/"
   */
  readonly excludeCharacters?: string;
}

/**
 *
 * A database secret.
 *
 * @resource aws_secretsmanager_secret
 */
export class DatabaseSecret extends secretsmanager.Secret {
  /** Uniquely identifies this class. */
  public static readonly PROPERTY_INJECTION_ID: string =
    "terraconstructs.aws.storage.docdb.DatabaseSecret";
  /**
   * the excluded characters for this Secret
   * @internal
   */
  public readonly _excludedCharacters: string;

  constructor(scope: Construct, id: string, props: DatabaseSecretProps) {
    const excludedCharacters = props.excludeCharacters ?? '"@/';

    // TERRACONSTRUCTS DEVIATION: upstream interpolates `Aws.STACK_NAME` (a CloudFormation
    // pseudo-parameter, `${AWS::StackName}`) into the description via `Fn::Join`. `core.Aws` is
    // not ported in this repo, and `TerraformStack` (cdktn) has no equivalent runtime-resolved
    // stack-name token -- `AwsStack.ofAwsConstruct(scope).node.id` (the construct ID the stack was
    // instantiated with, synth-time-known) is used as a plain string instead. Mirrors the identical
    // deviation on `../rds/database-secret.ts`.
    const stack = AwsStack.ofAwsConstruct(scope);

    super(scope, id, {
      secretName: props.secretName,
      description: `Generated by the CDK for stack: ${stack.node.id}`,
      encryptionKey: props.encryptionKey,
      // The CloudFormation resource provider for AWS::DocDB::DBCluster currently limits the DocDB master password to
      // 41 characters when pulling the password from secrets manager using a CloudFormation reference. This does not
      // line up with the CloudFormation resource specification which states a maximum of 100 characters:
      //
      // https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-masteruserpassword
      //
      // When attempting to exceed 41 characters, a deployment fails with the message:
      // Length of value for property {/MasterUserPassword} is greater than maximum allowed length {41}
      generateSecretString: {
        passwordLength: 41,
        secretStringTemplate: JSON.stringify({
          username: props.username,
          masterarn: props.masterSecret?.secretArn,
        }),
        generateStringKey: "password",
        excludeCharacters: excludedCharacters,
      },
    });

    this._excludedCharacters = excludedCharacters;
  }
}
