// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".
import type { IResolvable } from 'cdktn';
import type { provider } from '@cdktn/provider-cfncompat';

/**
 * Config for the Cfncompat Provider
 */
export interface CfncompatProviderConfig {
  /**
   * Session token for temporary credentials, typically provided after identity federation or MFA login.
   * Can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#token CfncompatProvider#token}
   * @stability stable
   */
  readonly token?: string;
  /**
   * Skip the AWS EC2 Instance Metadata API check.
   * Useful when running somewhere without a metadata API endpoint (setting to `true` prevents authenticating via IMDS).
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#skip_metadata_api_check CfncompatProvider#skip_metadata_api_check}
   * @stability stable
   */
  readonly skipMetadataApiCheck?: boolean | IResolvable;
  /**
   * Paths to shared credentials files. If not set, defaults to `~/.aws/credentials`.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#shared_credentials_files CfncompatProvider#shared_credentials_files}
   * @stability stable
   */
  readonly sharedCredentialsFiles?: Array<string>;
  /**
   * Paths to shared config files. If not set, defaults to `~/.aws/config`.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#shared_config_files CfncompatProvider#shared_config_files}
   * @stability stable
   */
  readonly sharedConfigFiles?: Array<string>;
  /**
   * The AWS secret key.
   * Can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment variable, or via a shared credentials file if `profile` is specified.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#secret_key CfncompatProvider#secret_key}
   * @stability stable
   */
  readonly secretKey?: string;
  /**
   * The AWS region used by cfncompat_custom_resource API calls.
   * Can also be sourced from the `AWS_REGION`/`AWS_DEFAULT_REGION` environment variables, a shared config file, or the EC2 Instance Metadata Service.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#region CfncompatProvider#region}
   * @stability stable
   */
  readonly region?: string;
  /**
   * The AWS profile name as set in the shared credentials/config files.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#profile CfncompatProvider#profile}
   * @stability stable
   */
  readonly profile?: string;
  /**
   * Comma-separated list of hosts that should not use HTTP or HTTPS proxies.
   * Can also be set using the `NO_PROXY`/`no_proxy` environment variables.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#no_proxy CfncompatProvider#no_proxy}
   * @stability stable
   */
  readonly noProxy?: string;
  /**
   * The maximum number of times an AWS API request is retried on failure. If not set, defaults to 25.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#max_retries CfncompatProvider#max_retries}
   * @stability stable
   */
  readonly maxRetries?: number;
  /**
   * Explicitly allow the provider to perform "insecure" SSL requests. Defaults to `false`.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#insecure CfncompatProvider#insecure}
   * @stability stable
   */
  readonly insecure?: boolean | IResolvable;
  /**
   * URL of a proxy to use for HTTPS requests when accessing the AWS API.
   * Can also be set using the `HTTPS_PROXY`/`https_proxy` environment variables.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#https_proxy CfncompatProvider#https_proxy}
   * @stability stable
   */
  readonly httpsProxy?: string;
  /**
   * URL of a proxy to use for HTTP requests when accessing the AWS API.
   * Can also be set using the `HTTP_PROXY`/`http_proxy` environment variables.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#http_proxy CfncompatProvider#http_proxy}
   * @stability stable
   */
  readonly httpProxy?: string;
  /**
   * Service endpoint URL overrides, primarily for testing against LocalStack.
   * Only used by cfncompat_custom_resource; the provider-defined functions make no AWS API calls.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#endpoints CfncompatProvider#endpoints}
   * @stability stable
   */
  readonly endpoints?: provider.CfncompatProviderEndpoints;
  /**
   * Default S3 bucket used for cfncompat_custom_resource response transport (the pre-signed PUT URL the custom resource handler writes its response to) when a cfncompat_custom_resource does not set its own `response_bucket`.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#custom_resource_bucket CfncompatProvider#custom_resource_bucket}
   * @stability stable
   */
  readonly customResourceBucket?: string;
  /**
   * Configuration for assuming an IAM role using a web identity token.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#assume_role_with_web_identity CfncompatProvider#assume_role_with_web_identity}
   * @stability stable
   */
  readonly assumeRoleWithWebIdentity?: provider.CfncompatProviderAssumeRoleWithWebIdentity;
  /**
   * Configuration for assuming an IAM role prior to making AWS API calls.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#assume_role CfncompatProvider#assume_role}
   * @stability stable
   */
  readonly assumeRole?: provider.CfncompatProviderAssumeRole;
  /**
   * The AWS access key.
   * Can also be sourced from the `AWS_ACCESS_KEY_ID` environment variable, or via a shared credentials file if `profile` is specified.
   *
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/cdktn-io/cfncompat/0.2.0/docs#access_key CfncompatProvider#access_key}
   * @stability stable
   */
  readonly accessKey?: string;
}
