export * from "./archive";
export * from "./event-bus";
export * from "./event-pattern";
export * from "./connection";
export * from "./input";
export * from "./on-event-options";
export * from "./queue-policy";
export * from "./queue";
export * from "./rule";
export * from "./schedule";
export * from "./target";
// kinesis
export * from "./kinesis-stream";
export * from "./resource-policy";

export * as targets from "./targets";

// generated by JSII Struct builder to please JSII pacman
export * from "./queue-config.generated";

// TODO: re-add QueueBase and Metrics support
// import "./sqs-augmentations.generated";
