package test

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/terraform"
	test_structure "github.com/gruntwork-io/terratest/modules/test-structure"
	"github.com/stretchr/testify/require"
	util "github.com/terraconstructs/base/integ/aws"
)

// Run the apps/secret-rotation.ts integration test: a real Postgres db.t3.micro
// in an isolated VPC with a Secrets Manager interface endpoint, and a
// `SecretRotation` deploying the AWS-published
// SecretsManagerRDSPostgreSQLRotationSingleUser SAR application. The app leaves
// rotateImmediatelyOnUpdate at its default (true), so a REAL rotation runs right
// after apply -- this test polls until it completes, proving the SAR stack, the
// rotation Lambda's network path (VPC endpoint + security groups), and the
// escaped excludeCharacters parameter all work end to end.
func TestSecretRotation(t *testing.T) {
	runEncryptionIntegrationTest(t, "secret-rotation", "us-east-1", validateSecretRotation)
}

func validateSecretRotation(t *testing.T, tfWorkingDir string, awsRegion string) {
	terraformOptions := test_structure.LoadTerraformOptions(t, tfWorkingDir)
	secretArn := util.LoadOutputAttribute(t, terraformOptions, "secret", "secretArn")

	// --- 1. Rotation is configured on the secret (schedule attached, Lambda wired). ---
	desc := util.DescribeSecret(t, awsRegion, secretArn)
	require.NotNil(t, desc.RotationEnabled, "RotationEnabled missing on secret")
	require.True(t, *desc.RotationEnabled, "rotation is not enabled")
	require.NotNil(t, desc.RotationLambdaARN, "no rotation lambda attached")
	rotationLambdaArn := *desc.RotationLambdaARN
	require.NotEmpty(t, rotationLambdaArn)
	t.Logf("secret-rotation: SAR rotation lambda attached: %s", rotationLambdaArn)

	// --- 2. A real rotation completes (rotateImmediatelyOnUpdate default fired on
	// apply). LastRotatedDate stays nil until the SAR Lambda finishes all four
	// rotation steps against the live database. ---
	deadline := time.Now().Add(12 * time.Minute)
	for desc.LastRotatedDate == nil && time.Now().Before(deadline) {
		time.Sleep(15 * time.Second)
		d, err := util.DescribeSecretE(t, awsRegion, secretArn)
		require.NoError(t, err)
		desc = d
	}
	require.NotNil(t, desc.LastRotatedDate,
		"rotation did not complete within deadline -- SAR lambda failed (check its CloudWatch logs)")
	t.Logf("secret-rotation: rotation completed at %s", desc.LastRotatedDate)

	// --- 3. Rotated value: still valid connection JSON, password regenerated by the
	// SAR Lambda honoring excludeCharacters. The exclusion set deliberately contains
	// `${` and `%{`; the password containing none of those characters live-proves
	// escapeTerraformTemplateLiteral delivered the parameter intact through two
	// Terraform template contexts. ---
	secretValue := aws.GetSecretValue(t, awsRegion, secretArn)
	var connection map[string]string
	require.NoError(t, json.Unmarshal([]byte(secretValue), &connection))
	require.Equal(t, "postgres", connection["engine"])
	require.NotEmpty(t, connection["host"])
	require.NotEmpty(t, connection["username"])
	require.NotEmpty(t, connection["password"])
	const excludedCharacters = " ;+%{}${}@'\"`/\\"
	for _, ch := range excludedCharacters {
		require.NotContains(t, connection["password"], string(ch),
			"rotated password contains excluded character %q -- excludeCharacters parameter did not arrive intact", ch)
	}
	t.Logf("secret-rotation: rotated password honors all %d excluded characters", len(excludedCharacters))

	// --- 4. The rotation function name is the deterministic TerraConstructs name
	// (also the SAR CloudFormation stack name -- see the TERRACONSTRUCTS DEVIATION
	// on `name` in src/aws/encryption/secret-rotation.ts). ---
	fnName := rotationLambdaArn[strings.LastIndex(rotationLambdaArn, ":")+1:]
	require.NotEmpty(t, fnName)
	t.Logf("secret-rotation: rotation function/stack name: %s", fnName)

	// --- Drift oracle: re-planning the already-applied stack must show zero changes.
	// Catches sentinel-default and read-back mismatches invisible at synth time, and
	// proves the SAR stack resource + rotation schedule read back cleanly. ---
	planExitCode := terraform.PlanExitCode(t, terraformOptions)
	require.Equal(t, terraform.DefaultSuccessExitCode, planExitCode,
		"expected `tofu plan -detailed-exitcode` to report no drift after apply (got exit code %d)", planExitCode)
}
