export * from "./bucket-destination";
export * from "./bucket-notifications";
export * from "./bucket-policy";
export * from "./bucket-source";
export * from "./bucket";
export * from "./location";
export * from "./util";
export * from "./origin-access-identity";
export * from "./parameter";

export * as targets from "./notification-targets";

// generated by JSII Struct builder to please JSII pacman
export * from "./website-config.generated";
export * from "./cors-config.generated";
export * from "./cors-rule-config.generated";
export * from "./lifecycle-config.generated";

// aws-dynamodb
export * from "./table";
export * from "./scalable-attribute-api";
// export * from "./table-v2";
// export * from "./table-v2-base";
export * from "./shared";
export * from "./capacity";
export * from "./billing";
export * from "./encryption";

export * from "./stream-grants";
export * from "./table-grants";

// aws-ecr
export * from "./ecr-repository";
export * from "./ecr-lifecycle";
export * from "./auth-token";

// s3 and ECR assets
export * as assets from "./assets";

// aws-rds
export * as rds from "./rds";

// aws-docdb
export * as docdb from "./docdb";

// aws-elasticache-alpha
export * as elasticache from "./elasticache";

// aws-neptune-alpha
export * as neptune from "./neptune";
