// https://github.com/aws/aws-cdk/blob/v2.233.0/packages/aws-cdk-lib/aws-batch/lib/compute-environment-base.ts

import { Construct } from "constructs";
import {
  AwsConstructBase,
  AwsConstructProps,
  IAwsConstruct,
} from "../../aws-construct";
import * as iam from "../../iam";

/**
 * Represents a ComputeEnvironment
 */
export interface IComputeEnvironment extends IAwsConstruct {
  /**
   * The name of the ComputeEnvironment
   *
   * @attribute
   */
  readonly computeEnvironmentName: string;

  /**
   * The ARN of this compute environment.
   *
   * @attribute
   */
  readonly computeEnvironmentArn: string;

  /**
   * The role Batch uses to perform actions on your behalf
   * in your account, such as provision instances to run your jobs
   *
   * @default - a serviceRole will be created for managed CEs, none for unmanaged CEs
   */
  readonly serviceRole?: iam.IRole;

  /**
   * Whether or not this ComputeEnvironment can accept jobs from a Queue.
   * Enabled ComputeEnvironments can accept jobs from a Queue and
   * can scale instances up or down.
   * Disabled ComputeEnvironments cannot accept jobs from a Queue or
   * scale instances up or down.
   *
   * If you change a ComputeEnvironment from enabled to disabled while it is executing jobs,
   * Jobs in the `STARTED` or `RUNNING` states will not
   * be interrupted. As jobs complete, the ComputeEnvironment will scale instances down to `minvCpus`.
   *
   * To ensure you aren't billed for unused capacity, set `minvCpus` to `0`.
   */
  readonly enabled: boolean;
}

/**
 * Props common to all ComputeEnvironments
 */
export interface ComputeEnvironmentProps extends AwsConstructProps {
  /**
   * The name of the ComputeEnvironment
   *
   * @default - generated by CloudFormation
   */
  readonly computeEnvironmentName?: string;

  /**
   * The role Batch uses to perform actions on your behalf
   * in your account, such as provision instances to run your jobs
   *
   * @default - a serviceRole will be created for managed CEs, none for unmanaged CEs
   */
  readonly serviceRole?: iam.IRole;

  /**
   * Whether or not this ComputeEnvironment can accept jobs from a Queue.
   * Enabled ComputeEnvironments can accept jobs from a Queue and
   * can scale instances up or down.
   * Disabled ComputeEnvironments cannot accept jobs from a Queue or
   * scale instances up or down.
   *
   * If you change a ComputeEnvironment from enabled to disabled while it is executing jobs,
   * Jobs in the `STARTED` or `RUNNING` states will not
   * be interrupted. As jobs complete, the ComputeEnvironment will scale instances down to `minvCpus`.
   *
   * To ensure you aren't billed for unused capacity, set `minvCpus` to `0`.
   *
   * @default true
   */
  readonly enabled?: boolean;
}

/**
 * Abstract base class for ComputeEnvironments
 *
 * @internal
 */
export abstract class ComputeEnvironmentBase
  extends AwsConstructBase
  implements IComputeEnvironment
{
  public abstract readonly computeEnvironmentName: string;
  public readonly serviceRole?: iam.IRole | undefined;
  public readonly enabled: boolean;
  public abstract readonly computeEnvironmentArn: string;

  public get outputs(): Record<string, any> {
    return {
      arn: this.computeEnvironmentArn,
      name: this.computeEnvironmentName,
    };
  }

  constructor(
    scope: Construct,
    id: string,
    props: ComputeEnvironmentProps = {},
  ) {
    super(scope, id, props);

    this.serviceRole = props?.serviceRole;
    this.enabled = props?.enabled ?? true;
  }
}
