// https://github.com/aws/aws-cdk/blob/v2.233.0/packages/aws-cdk-lib/aws-batch/lib/job-definition-base.ts

import { batchJobDefinition } from "@cdktn/provider-aws";
import { Lazy } from "cdktn";
import { Construct } from "constructs";
import { Duration } from "../../../duration";
import {
  AwsConstructBase,
  AwsConstructProps,
  IAwsConstruct,
} from "../../aws-construct";

/**
 * Represents a JobDefinition
 */
export interface IJobDefinition extends IAwsConstruct {
  /**
   * The ARN of this job definition
   *
   * @attribute
   */
  readonly jobDefinitionArn: string;

  /**
   * The name of this job definition
   *
   * @attribute
   */
  readonly jobDefinitionName: string;

  /**
   * The default parameters passed to the container
   * These parameters can be referenced in the `command` that
   * you give to the container
   *
   * @see https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters
   *
   * @default none
   */
  readonly parameters?: { [key: string]: any };

  /**
   * The number of times to retry a job.
   * The job is retried on failure the same number of attempts as the value.
   *
   * @default 1
   */
  readonly retryAttempts?: number;

  /**
   * Defines the retry behavior for this job
   *
   * @default - no `RetryStrategy`
   */
  readonly retryStrategies: RetryStrategy[];

  /**
   * The priority of this Job. Only used in Fairshare Scheduling
   * to decide which job to run first when there are multiple jobs
   * with the same share identifier.
   *
   * @default none
   */
  readonly schedulingPriority?: number;

  /**
   * The timeout time for jobs that are submitted with this job definition.
   * After the amount of time you specify passes,
   * Batch terminates your jobs if they aren't finished.
   *
   * @default - no timeout
   */
  readonly timeout?: Duration;

  /**
   * Add a RetryStrategy to this JobDefinition
   */
  addRetryStrategy(strategy: RetryStrategy): void;
}

/**
 * Props common to all JobDefinitions
 */
export interface JobDefinitionProps extends AwsConstructProps {
  /**
   * The name of this job definition
   *
   * // TERRACONSTRUCTS DEVIATION: upstream defaults this via CloudFormation's auto-generated
   * physical name. The `aws_batch_job_definition` Terraform resource requires `name` up front
   * (no `name_prefix` support), so concrete subclasses (`EcsJobDefinition`,
   * `MultiNodeJobDefinition`) resolve a default of `this.stack.uniqueResourceName(this)` when
   * this is omitted -- this abstract base creates no Terraform resource and performs no naming
   * resolution itself.
   *
   * @default - generated by the stack
   */
  readonly jobDefinitionName?: string;

  /**
   * The default parameters passed to the container
   * These parameters can be referenced in the `command` that
   * you give to the container
   *
   * @see https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters
   *
   * @default none
   */
  readonly parameters?: { [key: string]: any };

  /**
   * The number of times to retry a job.
   * The job is retried on failure the same number of attempts as the value.
   *
   * @default 1
   */
  readonly retryAttempts?: number;

  /**
   * Defines the retry behavior for this job
   *
   * @default - no `RetryStrategy`
   */
  readonly retryStrategies?: RetryStrategy[];

  /**
   * The priority of this Job. Only used in Fairshare Scheduling
   * to decide which job to run first when there are multiple jobs
   * with the same share identifier.
   *
   * @default none
   */
  readonly schedulingPriority?: number;

  /**
   * The timeout time for jobs that are submitted with this job definition.
   * After the amount of time you specify passes,
   * Batch terminates your jobs if they aren't finished.
   *
   * @default - no timeout
   */
  readonly timeout?: Duration;
}

/**
 * Define how Jobs using this JobDefinition respond to different exit conditions
 */
export class RetryStrategy {
  /**
   * Create a new RetryStrategy
   */
  public static of(action: Action, on: Reason) {
    return new RetryStrategy(action, on);
  }

  /**
   * The action to take when the job exits with the Reason specified
   */
  public readonly action: Action;

  /**
   * If the job exits with this Reason it will trigger the specified Action
   */
  public readonly on: Reason;

  constructor(action: Action, on: Reason) {
    this.action = action;
    this.on = on;
  }
}

/**
 * The Action to take when all specified conditions in a RetryStrategy are met
 */
export enum Action {
  /**
   * The job will not retry
   */
  EXIT = "EXIT",
  /**
   * The job will retry. It can be retried up to the number of times specified in `retryAttempts`.
   */
  RETRY = "RETRY",
}

/**
 * The corresponding Action will only be taken if *all* of the conditions specified here are met.
 */
export interface CustomReason {
  /**
   * A glob string that will match on the job exit code. For example, `'40*'` will match 400, 404, 40123456789012
   *
   * @default - will not match on the exit code
   */
  readonly onExitCode?: string;

  /**
   * A glob string that will match on the statusReason returned by the exiting job.
   * For example, `'Host EC2*'` indicates that the spot instance has been reclaimed.
   *
   * @default - will not match on the status reason
   */
  readonly onStatusReason?: string;

  /**
   * A glob string that will match on the reason returned by the exiting job
   * For example, `'CannotPullContainerError*'` indicates that container needed to start the job could not be pulled.
   *
   * @default - will not match on the reason
   */
  readonly onReason?: string;
}

/**
 * Common job exit reasons
 */
export class Reason {
  /**
   * Will match any non-zero exit code
   */
  static readonly NON_ZERO_EXIT_CODE: Reason = {
    onExitCode: "*",
  };

  /**
   * Will only match if the Docker container could not be pulled
   */
  static readonly CANNOT_PULL_CONTAINER: Reason = {
    onReason: "CannotPullContainerError:*",
  };

  /**
   * Will only match if the Spot instance executing the job was reclaimed
   */
  static readonly SPOT_INSTANCE_RECLAIMED: Reason = {
    onStatusReason: "Host EC2*",
  };

  /**
   * A custom Reason that can match on multiple conditions.
   * Note that all specified conditions must be met for this reason to match.
   */
  static custom(customReasonProps: CustomReason): Reason {
    return customReasonProps;
  }
}

/**
 * Abstract base class for JobDefinitions
 *
 * @internal
 */
export abstract class JobDefinitionBase
  extends AwsConstructBase
  implements IJobDefinition
{
  public abstract readonly jobDefinitionArn: string;
  public abstract readonly jobDefinitionName: string;

  public readonly parameters?: { [key: string]: any };
  public readonly retryAttempts?: number;
  public readonly retryStrategies: RetryStrategy[];
  public readonly schedulingPriority?: number;
  public readonly timeout?: Duration;

  public get outputs(): Record<string, any> {
    return {
      arn: this.jobDefinitionArn,
      name: this.jobDefinitionName,
    };
  }

  constructor(scope: Construct, id: string, props: JobDefinitionProps = {}) {
    super(scope, id, props);

    this.parameters = props.parameters;
    this.retryAttempts = props.retryAttempts;
    this.retryStrategies = props.retryStrategies ?? [];
    this.schedulingPriority = props.schedulingPriority;
    this.timeout = props.timeout;
  }

  addRetryStrategy(strategy: RetryStrategy): void {
    this.retryStrategies.push(strategy);
  }
}

/**
 * The subset of `BatchJobDefinitionConfig` populated by `JobDefinitionBase` and shared by every
 * concrete job definition (`EcsJobDefinition`, `MultiNodeJobDefinition`).
 *
 * // TERRACONSTRUCTS DEVIATION: upstream's `baseJobDefinitionProperties()` returns a
 * `CfnJobDefinitionProps` (CloudFormation L1 property bag) including a placeholder
 * `type: 'dummy'` that every subclass unconditionally overrides. There is no CFN L1 backing this
 * construct in TerraConstructs -- the `aws_batch_job_definition` resource is created by the
 * concrete subclasses, which set `name`/`type` themselves -- so this returns the analogous subset
 * of `batchJobDefinition.BatchJobDefinitionConfig` (retry_strategy/timeout are typed nested
 * blocks, not JSON) and omits the CFN-only `type` placeholder entirely.
 */
export type BaseJobDefinitionProperties = Pick<
  batchJobDefinition.BatchJobDefinitionConfig,
  "parameters" | "retryStrategy" | "schedulingPriority" | "timeout"
>;

/**
 * @internal
 */
export function baseJobDefinitionProperties(
  baseJobDefinition: JobDefinitionBase,
): BaseJobDefinitionProperties {
  return {
    parameters: stringifyParameters(baseJobDefinition.parameters),
    retryStrategy: {
      attempts: baseJobDefinition.retryAttempts,
      // NOTE: the `xxxToTerraform` conversion (camelCase -> snake_case) that the generated
      // `BatchJobDefinition._toTerraform()` normally applies via `cdktn.listMapper()` only runs
      // against plain arrays -- a `Lazy`-wrapped value is still a token (not `Array.isArray()`)
      // at that point, so `listMapper` passes it through unmapped and the eventually-resolved
      // array would keep its camelCase keys. Apply the mapper ourselves inside `produce()`.
      evaluateOnExit: Lazy.anyValue(
        {
          produce: () => {
            if (baseJobDefinition.retryStrategies.length === 0) {
              return undefined;
            }
            return baseJobDefinition.retryStrategies.map((strategy) =>
              batchJobDefinition.batchJobDefinitionRetryStrategyEvaluateOnExitToTerraform(
                {
                  action: strategy.action,
                  ...strategy.on,
                },
              ),
            );
          },
        },
        { omitEmptyArray: true },
      ),
    },
    schedulingPriority: baseJobDefinition.schedulingPriority,
    timeout: {
      attemptDurationSeconds: baseJobDefinition.timeout?.toSeconds(),
    },
  };
}

/**
 * `batchJobDefinition.BatchJobDefinitionConfig#parameters` is a flat string map, whereas upstream
 * (and this port's `JobDefinitionProps.parameters`) accepts arbitrary JSON-serializable values for
 * CFN template parity. Coerce non-string values so the Terraform provider's schema is satisfied.
 */
function stringifyParameters(parameters?: {
  [key: string]: any;
}): { [key: string]: string } | undefined {
  if (!parameters) {
    return undefined;
  }
  return Object.fromEntries(
    Object.entries(parameters).map(([key, value]) => [key, String(value)]),
  );
}
