// https://github.com/aws/aws-cdk/blob/v2.263.0/packages/aws-cdk-lib/aws-rds/lib/database-secret.ts

import { Annotations } from "cdktn";
import type { Construct } from "constructs";
import { DEFAULT_PASSWORD_EXCLUDE_CHARS } from "./private/util";
import { Duration } from "../../../duration";
import { md5hash } from "../../../helpers-internal";
import { AwsStack } from "../../aws-stack";
import * as secretsmanager from "../../encryption";
import type { IKey } from "../../encryption";

/**
 * Construction properties for a DatabaseSecret.
 */
export interface DatabaseSecretProps {
  /**
   * The username.
   */
  readonly username: string;

  /**
   * The database name, if not using the default one
   *
   * @default - whatever the secret generates after the attach method is run
   */
  readonly dbname?: string;

  /**
   * A name for the secret.
   *
   * @default - A name is generated by CloudFormation.
   */
  readonly secretName?: string;

  /**
   * The KMS key to use to encrypt the secret.
   *
   * @default default master key
   */
  readonly encryptionKey?: IKey;

  /**
   * The master secret which will be used to rotate this secret.
   *
   * @default - no master secret information will be included
   */
  readonly masterSecret?: secretsmanager.ISecret;

  /**
   * Characters to not include in the generated password.
   *
   * @default " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
   */
  readonly excludeCharacters?: string;

  /**
   * The number of days that Secrets Manager waits before it can delete the secret.
   *
   * TERRACONSTRUCTS DEVIATION: not present upstream (CloudFormation deletes
   * secrets immediately on stack delete; deletion recovery is a
   * Terraform-provider concept, `recovery_window_in_days`). Exposed as a
   * pass-through to `encryption.SecretProps.recoveryWindow` so deterministic
   * secret names can be re-created promptly (e.g. integ fixtures use
   * `Duration.days(0)`).
   *
   * @default - AWS default of 30 days
   */
  readonly recoveryWindow?: Duration;

  /**
   * Whether to replace this secret when the criteria for the password change.
   *
   * This is achieved by overriding the logical id of the AWS::SecretsManager::Secret
   * with a hash of the options that influence the password generation. This
   * way a new secret will be created when the password is regenerated and the
   * cluster or instance consuming this secret will have its credentials updated.
   *
   * TERRACONSTRUCTS DEVIATION: this flag is accepted for API parity but currently has NO
   * observable effect on the synthesized Terraform resource address. `DatabaseSecret` still
   * calls `overrideLogicalId()` internally (matching upstream), but by the time it runs,
   * `encryption.Secret`'s constructor has already read `this.resource.arn`/`.name`, which
   * eagerly resolves and caches the Terraform resource's `friendlyUniqueId` -- a later
   * `overrideLogicalId()` call can no longer change it. As a result, changing the
   * password-generation options will NOT force replacement of the secret (or a credential
   * rotation on dependents) the way it does in CloudFormation. See the implementation comment
   * in the constructor below for details. Fixing this requires `encryption.Secret` to accept a
   * caller-supplied logical id before constructing `this.resource`; out of scope for this port.
   *
   * @default false
   */
  readonly replaceOnPasswordCriteriaChanges?: boolean;

  /**
   * A list of regions where to replicate this secret.
   *
   * @default - Secret is not replicated
   */
  readonly replicaRegions?: secretsmanager.ReplicaRegion[];
}

/**
 * A database secret.
 *
 * @resource aws_secretsmanager_secret
 */
export class DatabaseSecret extends secretsmanager.Secret {
  /** Uniquely identifies this class. */
  public static readonly PROPERTY_INJECTION_ID: string =
    "terraconstructs.aws.storage.rds.DatabaseSecret";

  constructor(scope: Construct, id: string, props: DatabaseSecretProps) {
    const excludeCharacters =
      props.excludeCharacters ?? DEFAULT_PASSWORD_EXCLUDE_CHARS;

    // TERRACONSTRUCTS DEVIATION: upstream interpolates `Aws.STACK_NAME` (a CloudFormation
    // pseudo-parameter, `${AWS::StackName}`) into the description via `Fn::Join`. `core.Aws` is
    // not ported in this repo, and `TerraformStack` (cdktn) has no equivalent runtime-resolved
    // stack-name token -- `AwsStack.ofAwsConstruct(scope).node.id` (the construct ID the stack was
    // instantiated with, synth-time-known) is used as a plain string instead.
    const stack = AwsStack.ofAwsConstruct(scope);

    super(scope, id, {
      encryptionKey: props.encryptionKey,
      description: `Generated by the CDK for stack: ${stack.node.id}`,
      secretName: props.secretName,
      generateSecretString: {
        passwordLength: 30, // Oracle password cannot have more than 30 characters
        secretStringTemplate: JSON.stringify({
          username: props.username,
          dbname: props.dbname,
          masterarn: props.masterSecret?.secretArn,
        }),
        generateStringKey: "password",
        excludeCharacters,
      },
      replicaRegions: props.replicaRegions,
      recoveryWindow: props.recoveryWindow,
    });

    // TERRACONSTRUCTS DEVIATION: upstream overrides the CFN logical ID so that CloudFormation
    // replaces the secret when the password-generation options change (forcing dependents to pick
    // up new credentials). `overrideLogicalId()` is called here for parity with upstream, but it
    // currently has NO effect on the synthesized Terraform resource address: `encryption.Secret`'s
    // constructor (see `../../encryption/secret.ts`) already reads `this.resource.arn` /
    // `this.resource.name` above (via `super()`), and reading either attribute eagerly resolves and
    // caches `TerraformResource.friendlyUniqueId` -- once cached, a later `overrideLogicalId()` call
    // can no longer change what `friendlyUniqueId` returns. This is a structural mismatch between
    // CloudFormation's logical-ID model (mutable via `Ref`/`overrideLogicalId` any time before synth)
    // and Terraform's resource-addressing model (the address is locked in the moment any attribute
    // reference is built), not a bug specific to this construct -- see the identical limitation noted
    // in `test/aws/iam/role.from-role-arn.test.ts`. Fixing this for real would require
    // `encryption.Secret` to accept/apply a caller-supplied logical ID before constructing
    // `this.resource` (or before reading any of its attributes); out of scope for this port.
    if (props.replaceOnPasswordCriteriaChanges) {
      // Surface the no-op at synth time, not just in the doc comment (see the
      // TERRACONSTRUCTS DEVIATION on the prop).
      Annotations.of(this).addWarning(
        "replaceOnPasswordCriteriaChanges is currently a no-op in TerraConstructs: changing password-generation options will NOT force replacement of this secret. See the TERRACONSTRUCTS DEVIATION note on the prop.",
      );
      const hash = md5hash(
        JSON.stringify({
          // Use here the options that influence the password generation.
          // If at some point we add other password customization options
          // they should be added here below (e.g. `passwordLength`).
          excludeCharacters,
        }),
      );
      const logicalId = `${AwsStack.uniqueId(this)}${hash}`;

      this.resource.overrideLogicalId(logicalId.slice(-255)); // Take last 255 chars
    }
  }
}
